#!/bin/sh

# Append clubhouse ticket number if branch in the form:
# codependentcodr/ch1234/some-long-description

branch=$(git rev-parse --abbrev-ref HEAD)
IFS='/' read -ra array <<< "$branch"

if [[ ${#array[@]} -eq 3 ]]
then
    echo "[${array[1]}]" >> $1
fi
